import sqlite3
from typing import Final

from .core.constants import FOREIGN_KEYS
from .genius.tables import (
    GENIUS_ALBUM_INFO_TABLE_FOREIGN_KEYS,
    GENIUS_ALBUM_INFO_TABLE_META,
    GENIUS_ALBUM_INFO_TABLE_NAME,
    GENIUS_ALBUM_INFO_TABLE_PRIMARY_KEYS,
    GENIUS_ARTIST_INFO_TABLE_FOREIGN_KEYS,
    GENIUS_ARTIST_INFO_TABLE_META,
    GENIUS_ARTIST_INFO_TABLE_NAME,
    GENIUS_ARTIST_INFO_TABLE_PRIMARY_KEYS,
    GENIUS_DISCOGRAPHY_TABLE_FOREIGN_KEYS,
    GENIUS_DISCOGRAPHY_TABLE_META,
    GENIUS_DISCOGRAPHY_TABLE_NAME,
    GENIUS_DISCOGRAPHY_TABLE_PRIMARY_KEYS,
    GENIUS_SONG_INFO_TABLE_FOREIGN_KEYS,
    GENIUS_SONG_INFO_TABLE_META,
    GENIUS_SONG_INFO_TABLE_NAME,
    GENIUS_SONG_INFO_TABLE_PRIMARY_KEYS,
)
from .genius.tables import TABLES as GENIUS_TABLES
from .spotify.tables import (
    ALBUM_IMAGES_TABLE_FOREIGN_KEYS,
    ALBUM_IMAGES_TABLE_META,
    ALBUM_IMAGES_TABLE_NAME,
    ALBUM_IMAGES_TABLE_PRIMARY_KEYS,
    ALBUMS_TABLE_FOREIGN_KEYS,
    ALBUMS_TABLE_META,
    ALBUMS_TABLE_NAME,
    ALBUMS_TABLE_PRIMARY_KEYS,
    ARTIST_IMAGES_TABLE_FOREIGN_KEYS,
    ARTIST_IMAGES_TABLE_META,
    ARTIST_IMAGES_TABLE_NAME,
    ARTIST_IMAGES_TABLE_PRIMARY_KEYS,
    ARTISTS_TABLE_FOREIGN_KEYS,
    ARTISTS_TABLE_META,
    ARTISTS_TABLE_NAME,
    ARTISTS_TABLE_PRIMARY_KEYS,
    DISCOGRAPHY_TABLE_FOREIGN_KEYS,
    DISCOGRAPHY_TABLE_META,
    DISCOGRAPHY_TABLE_NAME,
    DISCOGRAPHY_TABLE_PRIMARY_KEYS,
    SONGS_TABLE_FOREIGN_KEYS,
    SONGS_TABLE_META,
    SONGS_TABLE_NAME,
    SONGS_TABLE_PRIMARY_KEYS,
)
from .spotify.tables import TABLES as SPOTIFY_TABLES
from .core.typing import CreateStatement

SQL_PRAGMA_STATEMENT: Final[str] = f"PRAGMA foreign_keys = {'ON' if FOREIGN_KEYS else 'OFF'};"

CURRENT_SCHEMA_VERSION: Final[int] = 1

VALID_SCHEMA_ID: Final[int] = 1
SCHEMA_META_TABLE: Final[CreateStatement] = f"""
CREATE TABLE IF NOT EXISTS schema_meta (
    id      INTEGER PRIMARY KEY CHECK (id = {VALID_SCHEMA_ID}),
    version INTEGER NOT NULL CHECK (version >= 0)
) STRICT;
"""

FULL_TABLES: Final[list[CreateStatement]] = GENIUS_TABLES + SPOTIFY_TABLES
SQL_CREATE_STATEMENTS: Final[str] = ("\n".join(FULL_TABLES)).strip()
if not SQL_CREATE_STATEMENTS.endswith(";"):
    raise RuntimeError("SQL_CREATE_STATEMENTS is malformed: does not end with a semicolon.")
